language: racket

env:
  - RACKET_VERSION=6.1
  - RACKET_VERSION=6.1.1
  - RACKET_VERSION=HEAD

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

install:
 - /usr/racket/bin/raco pkg install --deps search-auto
 - /usr/racket/bin/raco pkg install --deps search-auto cover
 
script:
 - /usr/racket/bin/raco test -x -p racket-rrb
 - /usr/racket/bin/raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
