language: racket

env:
  - RACKET_VERSION=6.1
  - RACKET_VERSION=HEAD

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

script:
 - ls
 - pwd
 - cd ..
 - /usr/racket/bin/raco pkg install --deps search-auto --link data/rrb
 - /usr/racket/bin/raco test -x -p rrb
